//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraveyardManagement.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlocareFaraProprietar
    {
        public int id { get; set; }
        public Nullable<int> alocareId { get; set; }
        public Nullable<int> solicitareAsistentaSociala { get; set; }
        public Nullable<int> nrAdeverintaInhumare { get; set; }
    
        public virtual AlocareLoc AlocareLoc { get; set; }
    }
}
