//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraveyardManagement.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domiciliu
    {
        public Domiciliu()
        {
            this.Persoana = new HashSet<Persoana>();
        }
    
        public int id { get; set; }
        public Nullable<int> stradaId { get; set; }
        public string numar { get; set; }
        public string alteInformatii { get; set; }
    
        public virtual Strada Strada { get; set; }
        public virtual ICollection<Persoana> Persoana { get; set; }
    }
}
