//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraveyardManagement.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istoric
    {
        public int id { get; set; }
        public string numeUtilizator { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> numarDocument { get; set; }
        public string detalii { get; set; }
    }
}
