//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraveyardManagement.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mormant
    {
        public Mormant()
        {
            this.AlocareLoc = new HashSet<AlocareLoc>();
            this.ProgramareInmormantare = new HashSet<ProgramareInmormantare>();
        }
    
        public int id { get; set; }
        public Nullable<int> cimitirId { get; set; }
        public string parcela { get; set; }
        public Nullable<int> numar { get; set; }
    
        public virtual ICollection<AlocareLoc> AlocareLoc { get; set; }
        public virtual Cimitir Cimitir { get; set; }
        public virtual ICollection<ProgramareInmormantare> ProgramareInmormantare { get; set; }
    }
}
