//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraveyardManagement.Model.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NecropolisEntities : DbContext
    {
        public NecropolisEntities()
            : base("name=NecropolisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AlocareCuProprietar> AlocareCuProprietar { get; set; }
        public DbSet<AlocareFaraProprietar> AlocareFaraProprietar { get; set; }
        public DbSet<AlocareLoc> AlocareLoc { get; set; }
        public DbSet<CerereLoc> CerereLoc { get; set; }
        public DbSet<Cimitir> Cimitir { get; set; }
        public DbSet<ContractConcesiune> ContractConcesiune { get; set; }
        public DbSet<Domiciliu> Domiciliu { get; set; }
        public DbSet<Istoric> Istoric { get; set; }
        public DbSet<Localitate> Localitate { get; set; }
        public DbSet<Mormant> Mormant { get; set; }
        public DbSet<Persoana> Persoana { get; set; }
        public DbSet<Poza> Poza { get; set; }
        public DbSet<ProgramareInmormantare> ProgramareInmormantare { get; set; }
        public DbSet<Reclamatie> Reclamatie { get; set; }
        public DbSet<Religie> Religie { get; set; }
        public DbSet<Stadiu> Stadiu { get; set; }
        public DbSet<Strada> Strada { get; set; }
    }
}
