//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraveyardManagement.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poza
    {
        public Poza()
        {
            this.AlocareCuProprietar = new HashSet<AlocareCuProprietar>();
        }
    
        public int id { get; set; }
        public byte[] continut { get; set; }
    
        public virtual ICollection<AlocareCuProprietar> AlocareCuProprietar { get; set; }
    }
}
