//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraveyardManagement.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamatie
    {
        public int id { get; set; }
        public string cnpReclamant { get; set; }
        public Nullable<System.DateTime> dataInregistrare { get; set; }
        public string detalii { get; set; }
    
        public virtual Persoana Persoana { get; set; }
    }
}
