//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraveyardManagement.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Strada
    {
        public Strada()
        {
            this.Domiciliu = new HashSet<Domiciliu>();
        }
    
        public int id { get; set; }
        public Nullable<int> localitateId { get; set; }
        public string nume { get; set; }
    
        public virtual ICollection<Domiciliu> Domiciliu { get; set; }
        public virtual Localitate Localitate { get; set; }
    }
}
